/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tajava_11376;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.FileHandler;
import java.util.logging.SimpleFormatter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.ParseException;
import java.awt.event.ActionEvent;
import com.sun.glass.events.KeyEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;

/**
 *
 * @author windows
 */
public class fakturPenjualan_11376 extends javax.swing.JFrame {

    /**
     * Creates new form fakturPenjualan_11376
     */
    
   private Connection con; 
    private Statement stm;
    private ResultSet rs;
    DefaultTableModel tb;
    int subTotal=0; //Variabel atau atribut untuk menampung nilai SubTotal
    String formatUang=""; //atribut untuk menampung hasil konversi uang integer menjadi format uang rupiah Rp.
    int uang=0; //atribut untuk menampung hasil mengembalikan format uang yang awalnya Rp. menjadi Integer angka lagi
   String dateChooser;
    public fakturPenjualan_11376() {
        initComponents();
        //Memanggil Method Koneksi Agar Terhubung ke Database
        koneksi();
        //Membuat Judul Setiap Kolom pada Table
        Object kol[]={"KODE","NAMA BARANG","SATUAN","JUMLAH","HARGA","TOTAL"};
        Object data[][]={};
        tb=new DefaultTableModel(data,kol);
        jTable1.setModel(tb);
        tampil_table();
        cancelkoreksiButton.setVisible(false);
       /*Cancel Koreksi set visible false  tujuanmya adalah pada awal 
        Aplikasi dijalankan, Button CancelKoreksi tidak muncul. Button Cancel Koreksi
        setVisible(true) akan terjadi bila Button Koreksi di klik. dan akan kembali
        setVisible(false) apabila button koreksi telah berjalan sepenuhnya atau button
        cancel koreksi diklik.
     */

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        noFakturField = new javax.swing.JTextField();
        tglFieldChooser = new com.toedter.calendar.JDateChooser();
        pembeliField = new javax.swing.JTextField();
        kasirField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        namaField = new javax.swing.JTextField();
        satuanField = new javax.swing.JTextField();
        jumlahfield = new javax.swing.JTextField();
        hargaField = new javax.swing.JTextField();
        totalField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Bayarfield = new javax.swing.JTextField();
        KembaliField = new javax.swing.JTextField();
        SUBTOTALField = new javax.swing.JTextField();
        inputButton = new javax.swing.JButton();
        koreksibutton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        keluarButton = new javax.swing.JButton();
        cancelkoreksiButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/icons8-note-26.png"))); // NOI18N
        jLabel1.setText(" FAKTUR PENJUALAN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Dibuat Oleh A11.2018.11376 - Latief Setiadi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        jLabel3.setText("No.Faktur");

        jLabel4.setText("Tanggal");

        jLabel5.setText("Pembeli");

        jLabel6.setText("Kasir");

        tglFieldChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglFieldChooserPropertyChange(evt);
            }
        });

        pembeliField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembeliFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noFakturField)
                    .addComponent(tglFieldChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kasirField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(pembeliField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(noFakturField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pembeliField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(kasirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tglFieldChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        jLabel7.setText("KODE BARANG");

        jLabel8.setText("NAMA BARANG");

        jLabel9.setText("SATUAN");

        jLabel10.setText("JUMLAH");

        jLabel11.setText("HARGA");

        jLabel12.setText("TOTAL");

        kode.setToolTipText("Ketik lalu Enter");
        kode.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });
        kode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kodeKeyPressed(evt);
            }
        });

        namaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaFieldActionPerformed(evt);
            }
        });

        jumlahfield.setToolTipText("Ketik lalu Enter");
        jumlahfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahfieldActionPerformed(evt);
            }
        });
        jumlahfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jumlahfieldKeyPressed(evt);
            }
        });

        totalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(satuanField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlahfield, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel8)
                        .addGap(322, 322, 322)
                        .addComponent(jLabel9)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalField)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(66, 66, 66))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satuanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel13.setText("SUB-TOTAL");

        jLabel14.setText("BAYAR");

        jLabel15.setText("KEMBALI");

        Bayarfield.setToolTipText("Ketik lalu Enter");
        Bayarfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BayarfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BayarfieldKeyReleased(evt);
            }
        });

        inputButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/icons8-home-24.png"))); // NOI18N
        inputButton.setText("Input");
        inputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputButtonActionPerformed(evt);
            }
        });

        koreksibutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/icons8-recycle-24.png"))); // NOI18N
        koreksibutton.setText("Koreksi");
        koreksibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koreksibuttonActionPerformed(evt);
            }
        });

        hapusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/icons8-trash-can-24.png"))); // NOI18N
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        simpanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/icons8-save-all-24.png"))); // NOI18N
        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        keluarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/icons8-exit-24.png"))); // NOI18N
        keluarButton.setText("Keluar");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });

        cancelkoreksiButton.setText("Cancel koreksi");
        cancelkoreksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelkoreksiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(inputButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(koreksibutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelkoreksiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)
                        .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(simpanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keluarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(36, 36, 36)
                                .addComponent(KembaliField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bayarfield, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(SUBTOTALField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(SUBTOTALField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelkoreksiButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputButton)
                        .addComponent(koreksibutton)
                        .addComponent(hapusButton)
                        .addComponent(simpanButton)
                        .addComponent(keluarButton))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Bayarfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KembaliField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void koneksi()
    {
        try{
            con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/tajava11376","root","");
            stm=con.createStatement();
            JOptionPane.showMessageDialog(null,"Koneksi Berhasil");
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
            Logger.getLogger(fakturPenjualan_11376.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    private void pembeliFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembeliFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pembeliFieldActionPerformed

    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldActionPerformed

    private void totalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldActionPerformed

    private void kodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodeKeyPressed
        // TODO add your handling code here:
        int harga;
        totalField.setText("");
        if(evt.getKeyCode()== KeyEvent.VK_ENTER) //Kondisi akan berjalan bila tombol Enter dipencet
        {
            if(isSame()==true){ //Kondisi bila terdapat data barang yang sama
                JOptionPane.showMessageDialog(null,"Data Sudah Ada!");
                kode.setText("");
            }
            else{
                if(!isWrongKodeBarang()){ //Kondisi jika Kode Barang tidak salah atau Kode Barang tidak tersedia di Database            
         try{
       rs=stm.executeQuery("select * from barang11376 where kode='"+kode.getText()+"'");
       while(rs.next())
       {
          namaField.setText(rs.getString("nama_brg"));
          satuanField.setText(rs.getString("satuan"));
          harga=Integer.parseInt(rs.getString("harga"));
           kurs_indonesia(harga); //mengubah menjadi format Mata Uang Rp. agar tampilan terlihat bagus
          hargaField.setText(this.formatUang);
          jumlahfield.setText("");
          jumlahfield.requestFocus();
       }
        }catch(SQLException e)
        {
             Logger.getLogger(fakturPenjualan_11376.class.getName()).log(Level.SEVERE,null,e);
        }
         Bayarfield.setText("");
         KembaliField.setText("");
                }
           
                else{
                    JOptionPane.showMessageDialog(null,"Kode barang tidak sesuai dengan data barang!");
                    kode.setText("");
                }
            }
         
        }
       
    }//GEN-LAST:event_kodeKeyPressed

    private void jumlahfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahfieldKeyPressed
        // TODO add your handling code here:
        int jumlah,harga,total;
       
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){   
        if(!koreksibutton.isEnabled()) //Kondisi untuk melakukan update atau koreksi
        {
            jumlahfield.requestFocus();
             jumlah=Integer.valueOf(jumlahfield.getText());
            format_reset(hargaField.getText()); // Mengembalikan format Uang Rupiah menjadi sebuah angka Integer
            harga=this.uang;
       total=jumlah*harga;
            kurs_indonesia(total); // mengubah ke Format Uang Rp.
       totalField.setText(this.formatUang);
       try{
       stm.executeUpdate("update temporary set nama_brg='"+namaField.getText()+"',satuan='"+satuanField.getText()+"'"+",jumlah='"+jumlahfield.getText()+"',harga='"+harga+"',total='"+total+"' where kode='"+kode.getText()+"'");
              
       reset_table();
       tampil_table();
       JOptionPane.showMessageDialog(null,"Data Telah Dikoreksi!\nMode Koreksi OFF");
       kode.setText("");
       namaField.setText("");
       satuanField.setText("");
       jumlahfield.setText("");
       hargaField.setText("");
       totalField.setText("");
       koreksibutton.setEnabled(true);
       cancelkoreksiButton.setVisible(false);
       kode.requestFocus();
           }catch(SQLException e)
       {
           Logger.getLogger(fakturPenjualan_11376.class.getName()).log(Level.SEVERE,null,e);
       }
        }
      
        else{
            if(!isSame()){ //Kondisi Jika Barang Tidak Sama dengan Barang yang  telah diinput.
       jumlah=Integer.valueOf(jumlahfield.getText());
       //harga=Integer.valueOf(hargaField.getText());
            format_reset(hargaField.getText());
            harga=this.uang;
       total=jumlah*harga;
            kurs_indonesia(total);
       totalField.setText(this.formatUang);
       try{
       stm.executeUpdate("insert into temporary values"+"('"+kode.getText()+"','"+namaField.getText()+"','"+satuanField.getText()+"','"+jumlahfield.getText()+"','"+harga+"','"+total+"')");
       reset_table();
       tampil_table();
        
           }catch(SQLException e)
       {
           Logger.getLogger(fakturPenjualan_11376.class.getName()).log(Level.SEVERE,null,e);
       }
        Bayarfield.setText("");
         KembaliField.setText("");
        
        }
            else{ 
                JOptionPane.showMessageDialog(null,"Data Sudah Ada!\n Pilih Koreksi Bila Ingin Update Data");
                kode.requestFocus();
            }
        }
    }
            
    }//GEN-LAST:event_jumlahfieldKeyPressed

    private void BayarfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BayarfieldKeyPressed
        // TODO add your handling code here:
        int bayar,kembalian;
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           kurs_indonesia(Integer.parseInt(Bayarfield.getText()));
           Bayarfield.setText(this.formatUang);
         int confirm=JOptionPane.showOptionDialog(this,"Yakin Ingin Membayar?","Perhatian !",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
         if(confirm==JOptionPane.YES_OPTION)
         {
             format_reset(Bayarfield.getText());
             bayar=this.uang;
             kembalian=bayar-this.subTotal;
             kurs_indonesia(kembalian);
             KembaliField.setText(this.formatUang);
             delete_all_temporary();
             inputButton.requestFocus();
         }
         else{
             Bayarfield.setText("");
         }
       }
       
       
    }//GEN-LAST:event_BayarfieldKeyPressed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeActionPerformed

    private void BayarfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BayarfieldKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BayarfieldKeyReleased

    private void tglFieldChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglFieldChooserPropertyChange
        // TODO add your handling code here:
        try{
            if(tglFieldChooser.getDate() != null)
            {
                String pattern ="yyyy-MM-dd";
                SimpleDateFormat format = new SimpleDateFormat(pattern);
                dateChooser=String.valueOf(format.format(tglFieldChooser.getDate()));
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"eror"+e);
        }
    }//GEN-LAST:event_tglFieldChooserPropertyChange

    private void inputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputButtonActionPerformed
        // TODO add your handling code here:
        noFakturField.setText("");
        tglFieldChooser.setCalendar(null);
        pembeliField.setText("");
        kasirField.setText("");
        kode.setText("");
        namaField.setText("");
        satuanField.setText("");
        jumlahfield.setText("");
        hargaField.setText("");
        totalField.setText("");
        reset_table();
        delete_all_temporary();
        SUBTOTALField.setText("");
        Bayarfield.setText("");
        KembaliField.setText("");
        noFakturField.requestFocus();
        
    }//GEN-LAST:event_inputButtonActionPerformed

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        // TODO add your handling code here:
        
        int confirm=JOptionPane.showConfirmDialog(null,"Apakah Yakin Ingin Keluar?","Konfirmasi Keluar!",JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_keluarButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        if(i>-1)
        {
            kode.setText(jTable1.getValueAt(i,0).toString());
            namaField.setText(jTable1.getValueAt(i,1).toString());
            satuanField.setText(jTable1.getValueAt(i,2).toString());
            jumlahfield.setText(jTable1.getValueAt(i,3).toString());
            hargaField.setText(jTable1.getValueAt(i,4).toString());
            totalField.setText(jTable1.getValueAt(i,5).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        if(kode.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Silahkan pilih data terlebih dahulu!");
        }
        else{
        int confirm=JOptionPane.showOptionDialog(this,"Yakin Dihapus?","Perhatian !",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(confirm==JOptionPane.YES_OPTION)
        {
            try{
                stm.executeUpdate("delete from temporary where kode = '"+kode.getText()+"'");
                 reset_table();
                tampil_table();
                JOptionPane.showMessageDialog(null,"Delete Sukses!");
                kode.setText("");
                namaField.setText("");
                satuanField.setText("");
                hargaField.setText("");
                jumlahfield.setText("");
                hargaField.setText("");
                totalField.setText("");
               
            }catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null,"Proses Hapus Gagal");
                Logger.getLogger(fakturPenjualan_11376.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
        }
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void koreksibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koreksibuttonActionPerformed
        // TODO add your handling code here:
      koreksibutton.setEnabled(false);
      JOptionPane.showMessageDialog(null,"Mode Koreksi Aktif!\nSilahkan Pilih Data Pada Table Tersedia");
      cancelkoreksiButton.setVisible(true);
    }//GEN-LAST:event_koreksibuttonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        String kode;
        int jumlah,totalharga;
        if((noFakturField.getText().isEmpty())||(tglFieldChooser.getDate().toString().isEmpty())||(pembeliField.getText().isEmpty())||(kasirField.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null,"Data ada yang kosong, lengkapi data terlebih dahulu!");
        }
        else{
        int confirm=JOptionPane.showConfirmDialog(null,"Data akan disimpan di laporan jual?","Konfirmasi Simpan!",JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION)
        {
            try{ 
                int i=jTable1.getRowCount();
                int x=0;
                while(x<i)
                {
                    kode=jTable1.getValueAt(x,0).toString();
                    jumlah=Integer.parseInt(jTable1.getValueAt(x,3).toString());
                    format_reset(jTable1.getValueAt(x,5).toString());
                    
                   stm.executeUpdate("insert into lapor_jual values"+"('"+noFakturField.getText()+"','"+dateChooser+"','"+pembeliField.getText()+"','"+kasirField.getText()+"','"+kode+"','"+jumlah+"','"+this.uang+"')");
                    x++;
                }
                JOptionPane.showMessageDialog(null,"Data Anda Berhasil Disimpan ^_^");
                }catch(SQLException e){
                Logger.getLogger(fakturPenjualan_11376.class.getName()).log(Level.SEVERE,null,e);
            
            }
        }
        }
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void jumlahfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahfieldActionPerformed

    private void cancelkoreksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelkoreksiButtonActionPerformed
        // TODO add your handling code here:
        koreksibutton.setEnabled(true);
        cancelkoreksiButton.setVisible(false);
    }//GEN-LAST:event_cancelkoreksiButtonActionPerformed

    private void tampil_table()
    {
        int hrg=0,ttl=0;
        try{
        String sql="select * from temporary";
        String kode,nama,satuan,jumlah,harga,total;
        rs=stm.executeQuery(sql);
        while(rs.next())
        {
            kode=rs.getString("kode");
            nama=rs.getString("nama_brg");
            satuan=rs.getString("satuan");
            jumlah=rs.getString("jumlah");
            hrg=Integer.parseInt(rs.getString("harga"));
            kurs_indonesia(hrg);
            harga=this.formatUang;
            ttl=Integer.parseInt(rs.getString("total"));
            this.subTotal=this.subTotal+ttl;
            kurs_indonesia(ttl);
            total=this.formatUang;
            tb.addRow(new Object[]{kode,nama,satuan,jumlah,harga,total});
            jTable1.setModel(tb);
            kurs_indonesia(this.subTotal);
       SUBTOTALField.setText(this.formatUang);
       
        }
        }catch(SQLException e)
        {
             Logger.getLogger(fakturPenjualan_11376.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    private void reset_table(){
        this.subTotal=0;
        tb.setRowCount(0);
        jTable1.setModel(tb);
    }
    private void delete_all_temporary()
    {
        
        try{
                stm.executeUpdate("delete from temporary");
        }catch(SQLException e)
        {
          Logger.getLogger(fakturPenjualan_11376.class.getName()).log(Level.SEVERE,null,e);
       
        }
        
    }
    
    private void kurs_indonesia(int harga)
    {
        try{
        int x =harga;
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
 
        formatRp.setCurrencySymbol("");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
 
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        this.formatUang="Rp."+kursIndonesia.format(x);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Format gagal");
        }
    }
    
    private void format_reset(String duit)
    {
        String x = duit;
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
 
        formatRp.setCurrencySymbol("Rp.");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
 
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        try {
            Number number = kursIndonesia.parse(x);
            int nilai = number.intValue();
            this.uang=nilai;
        } catch (ParseException ex) {
            System.out.println("Kesalahan Parsing");
        }
    }
    
    private boolean isSame()
    {
        int x=0;
        try{
            String sql="select * from temporary";
            rs=stm.executeQuery(sql);
            while(rs.next())
            {
                if(kode.getText().equals(rs.getString("kode")))
                {
                    x=1;
                }
            }
        }catch(SQLException e){
             Logger.getLogger(fakturPenjualan_11376.class.getName()).log(Level.SEVERE,null,e);
       
        }
        if(x==1)
        {
            return true;
        }
        else{
            return false;
        }
    }
    private boolean isWrongKodeBarang(){
        int x=0;
        try{
            String sql="select * from barang11376";
            rs=stm.executeQuery(sql);
            while(rs.next())
            {
                if(kode.getText().equals(rs.getString("kode")))
                {
                    x=1;
                }
            }
           
        }
        catch(SQLException e)
        {
             Logger.getLogger(fakturPenjualan_11376.class.getName()).log(Level.SEVERE,null,e);
       
        }
         if(x==0){
                return true;
            }
            else{
                return false;
            }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fakturPenjualan_11376.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fakturPenjualan_11376.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fakturPenjualan_11376.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fakturPenjualan_11376.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fakturPenjualan_11376().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bayarfield;
    private javax.swing.JTextField KembaliField;
    private javax.swing.JTextField SUBTOTALField;
    private javax.swing.JButton cancelkoreksiButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JTextField hargaField;
    private javax.swing.JButton inputButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlahfield;
    private javax.swing.JTextField kasirField;
    private javax.swing.JButton keluarButton;
    private javax.swing.JTextField kode;
    private javax.swing.JButton koreksibutton;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField noFakturField;
    private javax.swing.JTextField pembeliField;
    private javax.swing.JTextField satuanField;
    private javax.swing.JButton simpanButton;
    private com.toedter.calendar.JDateChooser tglFieldChooser;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
